export const DEFAULT_BIG_BLIND = 20;
export const DEFAULT_MAX_MESSAGE_LENGTH = 500;
export const MIN_NAME_LENGTH = 2;
export const MAX_NAME_LENGTH = 30;
export const MAX_INITIAL_CHIP_COUNT = 1000000;

export const MESSAGE_BURST_MAX = 5;
export const MESSAGE_BURST_THRESHOLD_MILLISECONDS = 3000;
export const MESSAGE_TOO_MANY_TIMEOUT_SECONDS = 5;
